# Generated by Django 5.1.4 on 2024-12-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_habitacion',
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_habitaciones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
